apiVersion: v1
kind: Service
metadata:
  name: tcpserver
  labels:
    name: tcpserver
spec:
  type: NodePort
  ports:
    - name: tcpserver
      port: 8081
      targetPort: 8081
  selector:
    app: tcpserver

