apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: udpserver
spec:
  replicas: 1
  selector:
    matchLabels:
        app: udpserver
  template:
    metadata:
      labels:
        app: udpserver
    spec:
      containers:
        - name: udpserver
          image: hub.soh.re/jmainguy/udpserver
          ports:
            - containerPort: 8082
          resources:
              limits:
                  cpu: "0.5"
                  memory: "100M"
              requests:
                  cpu: "0.5"
                  memory: "100M"
